id: P002975
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:02.049810
source_metadata:
  id: bdr:W1CZ2280
  title: མངོན་རྟོགས་རྒྱན་གྱི་ཊིཀྐ
  author: ''
  volumes:
    96b54d41b30d4729a238149e1ae546b8:
      image_group_id: I1CZ2314
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
